SELECT 
    ST.NUM AS [MAGAZA NO],
    ST.DESCRIPTION AS [MAĞAZA ADI],
    P.DESCRIPTION AS [POS ADI], 
    P.ID AS [POSID],
    CONVERT(VARCHAR(20), PST.CREATE_DATE, 113) AS [OLUŞTURULMA TARİHİ],
    CONVERT(VARCHAR(20), PST.MODIFY_DATE, 113) AS [İŞLENME TARİHİ],
    SUBSTRING(PST.FILE_NAME, 11, 2) + ' ' + 
    SUBSTRING(PST.FILE_NAME, 14, 2) + ' ' + 
    SUBSTRING(PST.FILE_NAME, 17, 4) AS [HANGİ GÜNÜN AKTARIMI],
    LEFT(PST.FILE_NAME, 20) AS [DOSYA ADI],
    PST.OK,
    CASE
        WHEN PST.OK = 0 THEN 'DOSYA BEKLİYOR'
        WHEN PST.OK = 10 THEN 'İŞLENİYOR'
        WHEN PST.OK = 20 THEN 'İŞLENDİ'
        WHEN PST.OK >= 30 THEN 'HATA'
        ELSE 'BİLİNMEYEN DURUM'
    END AS [DURUM]
FROM GENIUS3.POS_STOCK_TRANSFER PST WITH(NOLOCK)
JOIN GENIUS3.POS P WITH(NOLOCK) ON P.ID = PST.FK_POS
JOIN GENIUS3.STORE ST WITH(NOLOCK) ON ST.ID = PST.FK_STORE_LS
WHERE 
    PST.CREATE_DATE >= DATEADD(day, -1, GETDATE()) and fk_pos not IN (999)
ORDER BY 
    PST.CREATE_DATE DESC;